/**
 * PDFReport.jsx — the styled layout html2canvas captures into the PDF.
 * Rendered off-screen; never directly visible to the user.
 */
import { forwardRef } from "react";
import { formatRupees, formatPercent } from "../utils/formatter.js";
import { buildActionItems } from "./ActionPlan.jsx";
import { FY } from "../engine/constants.js";

const PDFReport = forwardRef(function PDFReport({ rec, input, insight }, ref) {
  const { comparison, oldResult, newResult } = rec;
  const winner = comparison.winner;
  const w = winner === "old" ? oldResult : newResult;
  const regimeName = winner === "old" ? "OLD TAX REGIME" : "NEW TAX REGIME";
  const items = buildActionItems(rec, input).slice(0, 4);
  const today = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <div className="pdf-report" ref={ref}>
      <div className="pdf-head">
        <h1 style={{ color: "#1b4332" }}>🟢 TaxSathi AI — Your Tax Plan</h1>
        <div style={{ textAlign: "right", fontSize: 12, color: "#888" }}>
          <div>FY {FY}</div>
          <div>Generated: {today}</div>
        </div>
      </div>

      <div className="pdf-banner">
        <div style={{ fontSize: 12, letterSpacing: "0.05em", color: "#666" }}>
          RECOMMENDED REGIME
        </div>
        <div className="r">{regimeName}</div>
        <div style={{ fontWeight: 600, color: "#52b788" }}>
          Annual tax saving vs other regime: {formatRupees(comparison.savings)}
        </div>
      </div>

      {insight && (
        <p style={{ fontSize: 13, lineHeight: 1.6, fontStyle: "italic", color: "#444" }}>
          “{insight}”
        </p>
      )}

      <h2>Your tax summary</h2>
      <Row k="Gross income" v={formatRupees(w.grossIncome)} />
      <Row k="Total deductions & exemptions" v={formatRupees(w.totalDeductions)} />
      <Row k="Taxable income" v={formatRupees(w.taxableIncome)} />
      <Row k="Final tax payable" v={formatRupees(w.finalTax)} bold />
      <Row k="Effective rate" v={formatPercent(w.effectiveRate)} />

      <h2>Both regimes compared</h2>
      <Row k="Old regime tax" v={formatRupees(oldResult.finalTax)} />
      <Row k="New regime tax" v={formatRupees(newResult.finalTax)} />

      {winner === "old" && (
        <>
          <h2>Your deduction breakdown</h2>
          <Row k="80C investments" v={formatRupees(oldResult.breakdown.sec80c)} />
          <Row k="80D health insurance" v={formatRupees(oldResult.breakdown.sec80d)} />
          <Row k="HRA exemption" v={formatRupees(oldResult.breakdown.hraExemption)} />
          <Row k="Home-loan interest (24b)" v={formatRupees(oldResult.breakdown.sec24b)} />
        </>
      )}

      <h2>Your action plan</h2>
      <ol style={{ paddingLeft: 18, fontSize: 13, lineHeight: 1.7 }}>
        {items.map((it, i) => (
          <li key={i}>
            <strong>{it.title}.</strong> {it.detail}
          </li>
        ))}
      </ol>

      <div className="pdf-foot">
        ⚠️ DISCLAIMER: This is AI-generated guidance for FY {FY}, not legal or
        financial advice. Consult a Chartered Accountant for complex situations.
        Generated by TaxSathi AI — free, no login.
      </div>
    </div>
  );
});

function Row({ k, v, bold }) {
  return (
    <div className="prow" style={bold ? { fontWeight: 700, color: "#1b4332" } : undefined}>
      <span>{k}</span>
      <span style={{ fontFamily: "monospace" }}>{v}</span>
    </div>
  );
}

export default PDFReport;
